### ISSUE TITLE
Demo codes not working?

### ISSUE THREAD

**Issue by jwmaseberg** [arduino-libraries/Arduino_Alvik#13]
Hi,
So I uploaded the drive.ino example on an alvik but it doesn't move the motors at all. I know the code is running as a put a serial print statement in the loop to check, but the motors never turn (with the alvik switch on). I have separately tried a python example and that did work, so the hardware should be fine...

**Comment by gbr1** [comment]
Hi @jwmaseberg can you tell me which version of arduino core for esp32 are you using?

@pillo79 please check this

**Comment by jwmaseberg** [comment]
I have Arduino AVR boards 1.8.6 installed.

**Comment by gbr1** [comment]
@jwmaseberg there should be a Arduino Nano ESP32 in your board menu. You can use also the left panel, board button, and search for arduino nano esp32. A version number such as 2.0.13 should appear. Please could you tell me that version number?

**Comment by jwmaseberg** [comment]
Ah yes, my fault. I have "Arduino ESP32 Boards 2.0.17" installed.

**Comment by gbr1** [comment]
Please try reverting to 2.0.13, we found an issue on serial pins on 2.0.17

Let me know if this fixs.

**Comment by jwmaseberg** [comment]
Yes, after reverting to "Arduino ESP32 Boards 2.0.13" the motors now turn using the drive code. Thanks.

**Comment by gbr1** [comment]
@pillo79 it is the bug introduced in Arduino Nano ESP32 core 2.0.17

@per1234 @jwmaseberg I leave this issue open as a promemoria and close with next core release

**Comment by pillo79** [comment]
@jwmaseberg A new version of the core was released, and this should hopefully be fixed. Can you give the latest version of "Arduino ESP32 Boards" a try and let us know? Thanks!

**Comment by jwmaseberg** [comment]
@pillo79 
If I update to "Arduino ESP32 Boards 2.0.18-20240930" and try to compile an example code I get an output of: 
"
xtensa-esp32s3-elf-g++: error: CreateProcess: No such file or directory
exit status 1
Compilation error: exit status 1
"

**Comment by pillo79** [comment]
@jwmaseberg That is quite an unexpected result. :sweat_smile: What OS are you using? 
Can you try deleting and re-adding the "Arduino ESP32 Boards" package, and/or exiting the IDE?
Also, if you have the "esp32" package by Espressif, try removing it.
Thanks for the feedback!

**Comment by jwmaseberg** [comment]
I does work with the Arduino ESP32 Boards 2.0.18 version on a windows machine I just tested that did not have any previous Arduino stuff on it. Hopefully I'll figure out what is going on with my usual computer at some point. -Thanks.

**Comment by gbr1** [comment]
I close this issue :D

Thanks @pillo79 for fast fixing 🚀 🚀 🚀
